sudo: required
services:
    - docker
before_install:
    - docker build -t daniel/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true daniel/react-test npm test -- --coverage

after_success:
    - docker build -t danielkim7500/multi-client ./client
    - docker build -t danielkim7500/multi-nginx ./nginx
    - docker build -t danielkim7500/multi-server ./server
    - docker build -t danielkim7500/multi-worker ./worker
    # Log in to the docker CLI - From Environments variables
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Task those images and push them to docker hub
    - docker push danielkim7500/multi-client
    - docker push danielkim7500/multi-nginx
    - docker push danielkim7500/multi-server
    - docker push danielkim7500/multi-worker

language: generic